/* ----------------------------------------------------------------------
   LAMMPS - Large-scale Atomic/Molecular Massively Parallel Simulator
   http://lammps.sandia.gov, Sandia National Laboratories
   Steve Plimpton, sjplimp@sandia.gov

   Copyright (2003) Sandia Corporation.  Under the terms of Contract
   DE-AC04-94AL85000 with Sandia Corporation, the U.S. Government retains
   certain rights in this software.  This software is distributed under
   the GNU General Public License.

   See the README file in the top-level LAMMPS directory.
------------------------------------------------------------------------- */

#ifdef FIX_CLASS

FixStyle(pass,FixPass)

#else

#ifndef LMP_FIX_PASS_H
#define LMP_FIX_PASS_H

#include "stdio.h"
#include "fix.h"

namespace LAMMPS_NS {

class FixPass : public Fix {
 public:
  FixPass(class LAMMPS *, int, char **);
  ~FixPass();
  int setmask();
  void end_of_step();

 private:
  int me,lid,rid,check;
  double xcoord;
  FILE *fp;
};

}

#endif
#endif

/* ERROR/WARNING messages:

E: Illegal ... command

Self-explanatory.  Check the input script syntax and compare to the
documentation for the command.  You can use -echo screen as a
command-line option when running LAMMPS to see the offending line.

E: Cannot open fix print file %s

The output file generated by the fix print command cannot be opened

*/
